### ISSUE TITLE
Wireframes desing

### ISSUE THREAD

**Issue by Enriketo** [Tech-Deal/Tech-Deal#5]
Define the first views for the project

**Comment by Johndev85** [comment]
## Initial project wareframes are created.

![1-Homepage](https://user-images.githubusercontent.com/53975214/93962119-a73fa100-fd1f-11ea-9b4c-cf24e1a87c31.png)
![2-Homepage-Search](https://user-images.githubusercontent.com/53975214/93962121-a7d83780-fd1f-11ea-9938-a39cc06156da.png)
![3-User-Page](https://user-images.githubusercontent.com/53975214/93962122-a870ce00-fd1f-11ea-99fe-8bccfe48cdef.png)
![4-Product-Detail-opcional](https://user-images.githubusercontent.com/53975214/93962124-a870ce00-fd1f-11ea-8bce-82afc410d414.png)
![5-Modal-Login](https://user-images.githubusercontent.com/53975214/93962127-a9096480-fd1f-11ea-939a-9f16613320c1.png)
![6-Modal-Sign-Up-](https://user-images.githubusercontent.com/53975214/93962128-a9a1fb00-fd1f-11ea-95a9-af8871d3f934.png)
![7-Homepage-tablet](https://user-images.githubusercontent.com/53975214/93962130-aa3a9180-fd1f-11ea-8322-101d993a5128.png)
![8-Homepage-Mobile](https://user-images.githubusercontent.com/53975214/93962131-aad32800-fd1f-11ea-95ae-6ec74b117972.png)
![9-Homepage-Search-Tablet](https://user-images.githubusercontent.com/53975214/93962132-aad32800-fd1f-11ea-838a-657e7d7509ee.png)
![10-Homepage-Search-Mobile](https://user-images.githubusercontent.com/53975214/93962133-ab6bbe80-fd1f-11ea-8187-8f1fb9d481f1.png)
